const questions = [
  // INFINITIVES (1-25)
  { id: 1, cat: "infinitive", q: "Pick out the infinitive and say how it is used: He came to see me.", a: "to see — Gerundial Infinitive (expressing purpose, adverbially modifying 'came').", bn: "উদ্দেশ্য বোঝাতে Gerundial Infinitive।" },
  { id: 2, cat: "infinitive", q: "Pick out the infinitive: To walk in the morning is good for health.", a: "To walk — Simple/Noun Infinitive used as the subject of the verb 'is'.", bn: "Subject হিসেবে Simple Infinitive।" },
  { id: 3, cat: "infinitive", q: "Is 'to' omitted correctly? I saw him go home.", a: "Yes. After 'see' (active voice) the infinitive without 'to' is used.", bn: "see-এর active voice-এর পরে to বাদ যায়।" },
  { id: 4, cat: "infinitive", q: "Correct if needed: He was seen come.", a: "Incorrect. Correct: He was seen to come. (In passive, 'to' is retained except with 'let'.)", bn: "Passive-এ to রাখতে হয়।" },
  { id: 5, cat: "infinitive", q: "He did nothing but laugh. Is the infinitive correct?", a: "Yes. After 'but' preceded by 'do', 'to' is omitted.", bn: "do-এর পরে but থাকলে to বাদ যায়।" },
  { id: 6, cat: "infinitive", q: "You had better go. Why is 'to' omitted?", a: "After 'had better / had rather / had sooner' the infinitive without 'to' is used.", bn: "had better-এর পরে to বাদ যায়।" },
  { id: 7, cat: "infinitive", q: "Distinguish: To err is human. vs He came to see me.", a: "To err = Simple (Noun) Infinitive (subject). to see = Gerundial Infinitive (purpose).", bn: "প্রথমটি Simple, দ্বিতীয়টি Gerundial।" },
  { id: 8, cat: "infinitive", q: "What type of infinitive? I am sorry to hear this.", a: "Gerundial Infinitive — adverbially modifying the adjective 'sorry'.", bn: "Adjective-কে modify করে Gerundial।" },
  { id: 9, cat: "infinitive", q: "Is this a Split Infinitive? I request you to kindly help me.", a: "Yes. Better: I request you to help me kindly.", bn: "Split Infinitive — এড়ানো ভালো।" },
  { id: 10, cat: "infinitive", q: "He is about to die. Parse 'to die'.", a: "Simple Infinitive used as object of the preposition 'about'.", bn: "Preposition-এর object হিসেবে Simple Infinitive।" },
  { id: 11, cat: "infinitive", q: "Give him a chair to sit on. Type of infinitive?", a: "Gerundial Infinitive — adjectivally modifying 'chair'.", bn: "Noun-কে qualify করে Gerundial।" },
  { id: 12, cat: "infinitive", q: "I could not but go there. Is 'to' correctly omitted?", a: "Yes. After 'but' when preceded by do/can, 'to' may be omitted.", bn: "cannot but-এর পরে to বাদ যায়।" },
  { id: 13, cat: "infinitive", q: "To speak the truth, I consider him a fool. Function?", a: "Gerundial Infinitive used absolutely / parenthetically.", bn: "Parenthetical / Absolute ব্যবহার।" },
  { id: 14, cat: "infinitive", q: "He was taught to swim. What kind of object is 'to swim'?", a: "Retained object (infinitive) after passive verb.", bn: "Passive-এর পরে retained object।" },
  { id: 15, cat: "infinitive", q: "Can you do this? Why no 'to'?", a: "After the auxiliary 'can' the bare infinitive is used.", bn: "Auxiliary can-এর পরে bare infinitive।" },
  { id: 16, cat: "infinitive", q: "How to test Simple vs Gerundial Infinitive?", a: "Expand it. Noun clause → Simple; adjectival/adverbial clause → Gerundial.", bn: "Expand করে noun clause হলে Simple, অন্যথায় Gerundial।" },
  { id: 17, cat: "infinitive", q: "I like to (go home). What is this construction?", a: "Colloquial ellipsis — verbal part dropped when already understood.", bn: "বোঝা গেলে verb বাদ দিয়ে শুধু to রাখা হয়।" },
  { id: 18, cat: "infinitive", q: "He seems to be clever. Function of the infinitive?", a: "Simple Infinitive used as complement of 'seems'.", bn: "Complement হিসেবে Simple Infinitive।" },
  { id: 19, cat: "infinitive", q: "Correct the Split Infinitive: to quickly do this.", a: "to do this quickly.", bn: "Adverb-কে verb-এর পরে রাখুন।" },
  { id: 20, cat: "infinitive", q: "They expect to pass. Function?", a: "Simple Infinitive used as object of 'expect'.", bn: "Object হিসেবে Simple Infinitive।" },
  { id: 21, cat: "infinitive", q: "Better be with the dead. Why no 'to'?", a: "After 'better' used absolutely, 'to' is often omitted.", bn: "Absolute 'better'-এর পরে to বাদ যায়।" },
  { id: 22, cat: "infinitive", q: "He need not go there. Correct?", a: "Yes. After 'need' (defective, negative) bare infinitive is used.", bn: "need not-এর পরে bare infinitive।" },
  { id: 23, cat: "infinitive", q: "Let him come. Why no 'to'?", a: "After 'let' the infinitive without 'to' is always used.", bn: "let-এর পরে সবসময় bare infinitive।" },
  { id: 24, cat: "infinitive", q: "He laughed to see me in trouble. Type?", a: "Gerundial Infinitive expressing cause/reason.", bn: "কারণ বোঝাতে Gerundial Infinitive।" },
  { id: 25, cat: "infinitive", q: "I ordered him to be punished. Type?", a: "Simple Infinitive used as object/complement of 'ordered'.", bn: "Object/Complement হিসেবে।" },

  // PARTICIPLES (26-40)
  { id: 26, cat: "participle", q: "What is a Present Participle?", a: "Form expressing ongoing action, formed by adding -ing.", bn: "চলমান কাজ বোঝায়, -ing যোগে গঠিত।" },
  { id: 27, cat: "participle", q: "What is a Past Participle?", a: "Form expressing completed action (ed/en/t etc.).", bn: "সম্পন্ন কাজ বোঝায়।" },
  { id: 28, cat: "participle", q: "Correct: Standing on the shore, my eye roams over the sea.", a: "Incorrect (unattached). Correct: While I am standing on the shore, my eye...", bn: "Unattached Participle — ঠিক করুন।" },
  { id: 29, cat: "participle", q: "God willing, we shall do it tomorrow. What construction?", a: "Nominative Absolute construction.", bn: "Nominative Absolute।" },
  { id: 30, cat: "participle", q: "A burning house vs A burnt house — difference?", a: "burning = Present (active); burnt = Past (passive).", bn: "Present = active, Past = passive।" },
  { id: 31, cat: "participle", q: "The scenery looks charming. Use of participle?", a: "Predicative use — completes the verb 'looks'.", bn: "Predicative ব্যবহার।" },
  { id: 32, cat: "participle", q: "This is a charming scenery. Use?", a: "Attributive use (Participial Adjective).", bn: "Attributive / Participial Adjective।" },
  { id: 33, cat: "participle", q: "Correct: Going home, my hat was blown off.", a: "As I was going home, my hat was blown off.", bn: "Dangling Participle এড়ান।" },
  { id: 34, cat: "participle", q: "Considering his age, he has done well. Is this correct?", a: "Yes. 'Considering' has become a preposition.", bn: "Preposition হয়ে যাওয়া participle — সঠিক।" },
  { id: 35, cat: "participle", q: "A well-read man — what does Past Participle express?", a: "Habit, state or character.", bn: "অভ্যাস/চরিত্র বোঝায়।" },
  { id: 36, cat: "participle", q: "We saw him running away. Parse 'running'.", a: "Present Participle used predicatively (object complement).", bn: "Object complement হিসেবে Present Participle।" },
  { id: 37, cat: "participle", q: "This done, they all left the place. Construction?", a: "Nominative Absolute.", bn: "Nominative Absolute।" },
  { id: 38, cat: "participle", q: "On entering the class, it was found empty. Correct it.", a: "On entering the class, the teacher found it empty.", bn: "Participle-এর logical subject দিন।" },
  { id: 39, cat: "participle", q: "I found him reading a book. Gerund or participle?", a: "Present Participle.", bn: "Present Participle।" },
  { id: 40, cat: "participle", q: "Having done the work, he returned home. Type?", a: "Perfect Participle (active).", bn: "Perfect Participle।" },

  // GERUNDS (41-55)
  { id: 41, cat: "gerund", q: "Walking is a good exercise. What is 'Walking'?", a: "Gerund used as subject.", bn: "Subject হিসেবে Gerund।" },
  { id: 42, cat: "gerund", q: "He is fond of riding. Function of 'riding'?", a: "Gerund, object of preposition 'of'.", bn: "Preposition-এর object।" },
  { id: 43, cat: "gerund", q: "I like your doing this. Why 'your'?", a: "Pronoun governing Gerund should be possessive.", bn: "Gerund-এর আগে Possessive case।" },
  { id: 44, cat: "gerund", q: "Correct: I insist on you to do this.", a: "I insist on your doing this.", bn: "insist on + possessive + gerund।" },
  { id: 45, cat: "gerund", q: "a sleeping room vs a sleeping dog — difference?", a: "sleeping room = Gerund; sleeping dog = Participial adjective.", bn: "প্রথমটি Gerund, দ্বিতীয়টি Participle।" },
  { id: 46, cat: "gerund", q: "There is a chance of the milk turning. Why not milk's?", a: "With lifeless things, participle construction is preferred.", bn: "জড়বস্তুর ক্ষেত্রে Participle ব্যবহার।" },
  { id: 47, cat: "gerund", q: "Women having the vote reduces men's power. Correct it.", a: "Women's having the vote reduces men's power.", bn: "Fused Participle ভুল — Possessive ব্যবহার করুন।" },
  { id: 48, cat: "gerund", q: "He is engaged in the writing of a letter. What is 'writing'?", a: "Verbal Noun (the + -ing + of).", bn: "Verbal Noun।" },
  { id: 49, cat: "gerund", q: "Distinguish Gerund and Verbal Noun.", a: "Gerund = verb+noun (can take object). Verbal Noun = pure noun (the ... of).", bn: "Verbal Noun-এ the ও of থাকে।" },
  { id: 50, cat: "gerund", q: "Abstain from speaking evil. Why not 'to speak'?", a: "Idiom requires Gerund after 'abstain from'.", bn: "Idiom অনুসারে Gerund।" },
  { id: 51, cat: "gerund", q: "I am tired of waiting. Parse 'waiting'.", a: "Gerund, object of 'of'.", bn: "Preposition-এর object Gerund।" },
  { id: 52, cat: "gerund", q: "Further waiting is useless. What is 'waiting'?", a: "Gerund used as subject.", bn: "Subject Gerund।" },
  { id: 53, cat: "gerund", q: "He went away weeping. Is 'weeping' a gerund?", a: "No. Present Participle (manner).", bn: "Present Participle (manner)।" },
  { id: 54, cat: "gerund", q: "Success is attained by working diligently. Parse 'working'.", a: "Gerund, object of 'by'.", bn: "by-এর object Gerund।" },
  { id: 55, cat: "gerund", q: "I depend on the wall being built at once. What is this?", a: "Gerundive Participle.", bn: "Gerundive Participle।" },

  // AUXILIARIES (56-75)
  { id: 56, cat: "auxiliary", q: "You must do it. What does 'must' express?", a: "Compulsion / obligation.", bn: "বাধ্যবাধকতা।" },
  { id: 57, cat: "auxiliary", q: "You must have done it. Meaning?", a: "Past certainty.", bn: "অতীতের নিশ্চয়তা।" },
  { id: 58, cat: "auxiliary", q: "May I come? What does 'May' express?", a: "Permission.", bn: "অনুমতি।" },
  { id: 59, cat: "auxiliary", q: "Can vs May — difference?", a: "Can = ability; May = permission.", bn: "Can = সামর্থ্য, May = অনুমতি।" },
  { id: 60, cat: "auxiliary", q: "I shall go. Simple futurity or determination?", a: "Simple futurity (1st person).", bn: "সাধারণ ভবিষ্যৎ (১ম পুরুষ)।" },
  { id: 61, cat: "auxiliary", q: "You shall go. Meaning?", a: "Command / determination of the speaker.", bn: "বক্তার আদেশ/দৃঢ়সংকল্প।" },
  { id: 62, cat: "auxiliary", q: "I will go there. Meaning?", a: "Determination or promise of the speaker.", bn: "বক্তার দৃঢ়সংকল্প/প্রতিশ্রুতি।" },
  { id: 63, cat: "auxiliary", q: "Shall I go? Possible meanings?", a: "Simple enquiry or asking desire/command.", bn: "ভবিষ্যৎ জিজ্ঞাসা বা ইচ্ছা জানতে চাওয়া।" },
  { id: 64, cat: "auxiliary", q: "Will you go? Meaning?", a: "Asking intention or desire of the person spoken to.", bn: "ইচ্ছা/অভিপ্রায় জানতে চাওয়া।" },
  { id: 65, cat: "auxiliary", q: "You should speak the truth. Force of 'should'?", a: "Duty / obligation.", bn: "কর্তব্য/বাধ্যবাধকতা।" },
  { id: 66, cat: "auxiliary", q: "I should like to do it. Force?", a: "Modesty (1st person).", bn: "নম্রতা প্রকাশ।" },
  { id: 67, cat: "auxiliary", q: "He would go to the Maidan while in Calcutta. Meaning?", a: "Past habit.", bn: "অতীতের অভ্যাস।" },
  { id: 68, cat: "auxiliary", q: "Correct: I dared not to leave the room.", a: "I dared not leave the room.", bn: "dare not-এর পরে to বাদ।" },
  { id: 69, cat: "auxiliary", q: "He need not do it. Is 'needs' possible?", a: "No. Defective need uses 'need' (not needs) in neg/interrog.", bn: "Defective need-এ needs হয় না।" },
  { id: 70, cat: "auxiliary", q: "You ought to have gone there. Why perfect infinitive?", a: "To refer to past unfulfilled obligation.", bn: "অতীতের অপূর্ণ কর্তব্য বোঝাতে।" },
  { id: 71, cat: "auxiliary", q: "The school shall be closed tomorrow. Who can say this?", a: "Only someone in authority.", bn: "কর্তৃপক্ষই বলতে পারেন।" },
  { id: 72, cat: "auxiliary", q: "Might I go now? Force of 'Might'?", a: "Mild / polite request.", bn: "নম্র অনুরোধ।" },
  { id: 73, cat: "auxiliary", q: "He might have recovered if he had proper nursing. Meaning?", a: "Unfulfilled past possibility.", bn: "অপূর্ণ শর্তের কারণে অতীত সম্ভাবনা।" },
  { id: 74, cat: "auxiliary", q: "I have to go. What does 'have to' express?", a: "Obligation / necessity.", bn: "বাধ্যবাধকতা।" },
  { id: 75, cat: "auxiliary", q: "Do go there. Function of 'Do'?", a: "Auxiliary used for emphasis.", bn: "জোর দেওয়ার জন্য।" },

  // CONDITIONALS (76-90)
  { id: 76, cat: "conditional", q: "If it rains, I shall not go. Which Type?", a: "Type I (Real/Possible).", bn: "Type I — সম্ভাব্য শর্ত।" },
  { id: 77, cat: "conditional", q: "If I had money, I would lend you some. Type & meaning?", a: "Type II — Unreal present.", bn: "Type II — বর্তমানের অসম্ভাব্য শর্ত।" },
  { id: 78, cat: "conditional", q: "If I had tried sincerely, I would have got the post. Type?", a: "Type III — Unreal past.", bn: "Type III — অতীতের অসম্পূর্ণ শর্ত।" },
  { id: 79, cat: "conditional", q: "If he (come) today, he (meet) my brother.", a: "If he comes today, he will meet my brother.", bn: "Type I: Present + will।" },
  { id: 80, cat: "conditional", q: "If I (be) you, I (not do) it.", a: "If I were you, I should/would not do it.", bn: "Type II: were + would/should।" },
  { id: 81, cat: "conditional", q: "If you had asked me, I (do) it.", a: "If you had asked me, I would have done it.", bn: "Type III: had + would have।" },
  { id: 82, cat: "conditional", q: "If you heat ice, it turns into water. Why both present?", a: "Type I with present reference (universal truth).", bn: "চিরন্তন সত্য — উভয় Present।" },
  { id: 83, cat: "conditional", q: "If you meet him, ask him to ring me up. Structure?", a: "Type I with imperative in main clause.", bn: "Main clause-এ Imperative।" },
  { id: 84, cat: "conditional", q: "Had we met him there, we could have told him. What happened to 'If'?", a: "If omitted + Had inverted (formal Type III).", bn: "If বাদ দিয়ে Had দিয়ে inversion।" },
  { id: 85, cat: "conditional", q: "If he (work) all night, he would finish in time.", a: "If he worked all night, he would finish in time.", bn: "Type II।" },
  { id: 86, cat: "conditional", q: "If only you had started early, you (reach) in time.", a: "If only you had started early, you would have reached in time.", bn: "Type III।" },
  { id: 87, cat: "conditional", q: "If the earth suddenly (stop) spinning, we would all fly off it.", a: "If the earth suddenly stopped spinning, we would all fly off it.", bn: "Type II — কাল্পনিক।" },
  { id: 88, cat: "conditional", q: "What is the tense of the if-clause in Type II?", a: "Past tense (subjunctive, not true past).", bn: "Past tense (subjunctive)।" },
  { id: 89, cat: "conditional", q: "If you will wait a moment, I will bring my purse. Correct?", a: "Yes. Polite request — both clauses can be future.", bn: "নম্র অনুরোধে উভয় Future সম্ভব।" },
  { id: 90, cat: "conditional", q: "If he had taken your advice, he would be successful now. Mixed?", a: "Yes. Type III if-clause + Type II main clause.", bn: "Mixed conditional।" },

  // SEQUENCE OF TENSES (91-100)
  { id: 91, cat: "sequence", q: "He was sorry that I ___ not help him. (can/could)", a: "could (Principal past → Dependent past).", bn: "Principal Past হলে Dependent-ও Past।" },
  { id: 92, cat: "sequence", q: "He did not know that the earth ___ round. (moves/moved)", a: "moves (Universal truth remains Present).", bn: "চিরন্তন সত্য Present থাকে।" },
  { id: 93, cat: "sequence", q: "I could not go as I ___ suffering from fever. (am/was)", a: "was.", bn: "Past sequence।" },
  { id: 94, cat: "sequence", q: "Rule I of Sequence of Tenses?", a: "If Principal is Present or Future, Dependent may be any tense.", bn: "Principal Present/Future হলে Dependent যেকোনো tense।" },
  { id: 95, cat: "sequence", q: "Rule II of Sequence of Tenses?", a: "If Principal is Past, Dependent should be corresponding Past (except universal truth).", bn: "Principal Past → Dependent Past (সত্য ছাড়া)।" },
  { id: 96, cat: "sequence", q: "He said that examples ___ better than precept. (are/were)", a: "are (or were). Universal/habitual can stay Present.", bn: "Habitual/universal — Present রাখা যায়।" },
  { id: 97, cat: "sequence", q: "When I called at the house he ___ gone away. (has/had)", a: "had (Past Perfect).", bn: "Past Perfect।" },
  { id: 98, cat: "sequence", q: "I learnt that he ___ ill, but ___ not go to see him.", a: "was; did.", bn: "উভয় Past।" },
  { id: 99, cat: "sequence", q: "He failed because he ___ not listen to advice. (does/did)", a: "did.", bn: "Past sequence।" },
  { id: 100, cat: "sequence", q: "Rule III of Sequence of Tenses?", a: "When Dependent denotes comparison or works as adjective, any tense may follow any tense.", bn: "তুলনা বা adjective clause-এ যেকোনো tense সম্ভব।" }
];
